site_name: FitLife Documentation
theme: readthedocs
docs_dir: architecture
markdown_extensions:
  - md_in_html
  - plantuml_markdown
  - pymdownx.superfences
plugins:
  - search
  # - plantuml:
  #     puml_url: https://www.plantuml.com/plantuml/